server:
  port: 7070
dubbo:
  application:
    name: demo-server
    qos-port: 22222
  registry:
    address: 192.168.0.10:2181,192.168.0.11:2181,192.168.0.12:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.lding.ds